server:
  port: 8081
#slf4j
logging:
  config:
    classpath: logback.xml
  level:
    com.hjt.course01.dao: trace
# 配置多个微服务的地址
url:
  # 订单微服务的地址
  orderUrl: http://localhost:80025
  # 用户微服务的地址
  userUrl: http://localhost:80035
  # 购物车微服务的地址
  shoppingUrl: http://localhost:80045